"""Minimal stubs for the `jq` package (C extension, ships no type information)."""

from typing import Any

class _Program:
    def input_value(self, value: Any) -> _Program: ...
    def input_text(self, text: str) -> _Program: ...
    def first(self, default: Any = ...) -> Any: ...
    def all(self) -> list[Any]: ...

def compile(program: str) -> _Program: ...
